name: Nightly

on:
  schedule:
    - cron: '0 2 * * *' # Daily at 02:00 runs only on default branch
  workflow_dispatch:

jobs:
  nightly:
    name: build / php-${{ matrix.php }}-${{ matrix.ts }}-${{ matrix.name }}-${{ matrix.compiler }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: linux, php: '8.2', ts: 'nts', compiler: 'gcc',   os: ubuntu-20.04 }
          - { name: mac,   php: '8.2', ts: 'nts', compiler: 'clang', os: macos-11 }

    steps:
      - uses: actions/checkout@v2

      # configure spx artifact name in next format:
      #   {php}-{ts}-{os.name}-{compiler}
      #   spx-php-8.1-nts-Linux-gcc
      - name: Set artifact name
        id: setup-artifact
        run: |
          echo "::set-output name=spx_file_name::spx-php-${{ matrix.php }}-${{ matrix.ts }}-${{ matrix.name }}-${{ matrix.compiler }}"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        if: runner.os == 'macOS'
        run: brew install zlib

      - name: phpize
        run: phpize

      - name: Configure
        run: |
          if [ "${{ runner.os }}" = "macOS" ]; then
            ./configure --with-zlib-dir=$(brew --prefix)/opt/zlib
          else
            ./configure
          fi

      - name: Compile
        run: |
          make -j"$(getconf _NPROCESSORS_ONLN)"
          sudo make install

      - name: Extension Info
        run: |
          php --ini
          php -d extension=./modules/spx.so --ri spx

      - name: Run Tests
        run: make test
        env:
          NO_INTERACTION: 1
          REPORT_EXIT_STATUS: 1
          TEST_PHP_ARGS: "--show-diff"

      - name: Upload build artifacts after Failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: debug-${{ steps.setup-artifact.outputs.spx_file_name }}
          path: |
            ${{ github.workspace }}/*.log
            ${{ github.workspace }}/tests/*.log
          retention-days: 7
